#!/bin/bash
ln -sf "$HOME/dotfiles/config/btop" "$HOME/.config/btop"
ln -sf "$HOME/dotfiles/config/dunst" "$HOME/.config/dunst"
ln -sf "$HOME/dotfiles/config/eww" "$HOME/.config/eww"
ln -sf "$HOME/dotfiles/config/fastfetch" "$HOME/.config/fastfetch"
ln -sf "$HOME/dotfiles/config/hypr" "$HOME/.config/hypr"
ln -sf "$HOME/dotfiles/config/kitty" "$HOME/.config/kitty"
ln -sf "$HOME/dotfiles/config/oh-my-posh" "$HOME/.config/oh-my-posh"
ln -sf "$HOME/dotfiles/config/spicetify" "$HOME/.config/spicetify"
ln -sf "$HOME/dotfiles/config/swaync" "$HOME/.config/swaync"
ln -sf "$HOME/dotfiles/config/waybar" "$HOME/.config/waybar"
ln -sf "$HOME/dotfiles/config/wofi" "$HOME/.config/wofi"
ln -sf "$HOME/dotfiles/config/zed" "$HOME/.config/zed"
ln -sf "$HOME/dotfiles/config/bash/.bashrc" "$HOME/.bashrc"
ln -sf "$HOME/dotfiles/config/zsh/.zshrc" "$HOME/.zshrc"
ln -sf "$HOME/dotfiles/config/wallpapers" "$HOME/wallpapers"
