source = /home/arianne/dotfiles/config/hypr/desktop/monitors.conf
source = /home/arianne/dotfiles/config/hypr/desktop/programs.conf
source = /home/arianne/dotfiles/config/hypr/desktop/autostart.conf
source = /home/arianne/dotfiles/config/hypr/desktop/bindings.conf
