foreground         #c4c2c6
background         #160c1c
background_opacity 1.0
cursor             #c4c2c6

active_tab_foreground     #160c1c
active_tab_background     #c4c2c6
inactive_tab_foreground   #c4c2c6
inactive_tab_background   #160c1c

active_border_color   #c4c2c6
inactive_border_color #160c1c
bell_border_color     #961EAA

color0       #160c1c
color8       #685b70
color1       #961EAA
color9       #961EAA
color2       #A92FCE
color10      #A92FCE
color3       #BD3FC8
color11      #BD3FC8
color4       #A24CD5
color12      #A24CD5
color5       #D45EEF
color13      #D45EEF
color6       #788ED5
color14      #788ED5
color7       #c4c2c6
color15      #c4c2c6
