foreground         #c4c1c3
background         #150911
background_opacity 1.0
cursor             #c4c1c3

active_tab_foreground     #150911
active_tab_background     #c4c1c3
inactive_tab_foreground   #c4c1c3
inactive_tab_background   #150911

active_border_color   #c4c1c3
inactive_border_color #150911
bell_border_color     #97576E

color0       #150911
color8       #6c5866
color1       #97576E
color9       #97576E
color2       #746685
color10      #746685
color3       #AA728B
color11      #AA728B
color4       #CB7891
color12      #CB7891
color5       #B78DA2
color13      #B78DA2
color6       #DA9EAE
color14      #DA9EAE
color7       #c4c1c3
color15      #c4c1c3
